### ISSUE TITLE
Jumbotron css padding too big in codelab tutorial

### ISSUE THREAD

**Issue by wware** [yeoman/yeoman.io#304]
I was going through the [codelab tutorial](http://yeoman.io/codelab/write-app.html) and noticed that the colored parts of the controls ("Add", "X") were too tall. I dug around and fixed the following apparent bug around line 49 in `app/styles/main.css`:

``` css
.jumbotron .btn {
  font-size: 21px;
  /* padding: 14px 24px;    <== BAD */
  padding: 1px 24px;     /* <== GOOD */
}
```

If I don't put in this fix, this is what I see:
![screen shot 2014-08-25 at 4 34 03 pm](https://cloud.githubusercontent.com/assets/246731/4036157/345f8416-2c97-11e4-9315-2966e315d6e9.png)
